language: scala
scala:
  - 2.13.5
env:
  - akkaVersion=2.6.14
  - akkaVersion=2.6.13
  - akkaVersion=2.6.12
  - akkaVersion=2.6.11
  - akkaVersion=2.6.10
  - akkaVersion=2.6.9
  - akkaVersion=2.5.32
script:
  - sbt ++$TRAVIS_SCALA_VERSION -DakkaVersion=$akkaVersion test
